config/routes.rb
Rails.application.routes.draw do
  root_path = 'phrases#index'

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    resources :pages,         only: [:index, :show]
    resources :phrases,       only: [:index, :show]
    resources :searches,      only: [:index, :create]
    resources :translations,  only: [:show]
    resources :user_sessions, only: [:new, :create]

    resources :users, only: [:new, :create] do
      member do
        get :activate
      end
    end

    get '/sign_up',  to: 'users#new',             as: :sign_up
    get '/sign_in',  to: 'user_sessions#new',     as: :sign_in
    get '/sign_out', to: 'user_sessions#destroy', as: :sign_out
    
    namespace :admin do
      resources :users, :searches, :tags, :phrases
      root to: root_path 
    end
  end

  root to: root_path 
  get '/:locale', to: root_path

  # Any other routes are handled here (as ActionDispatch prevents RoutingError from hitting ApplicationController::rescue_action)
  # http://unix.stackexchange.com/questions/72086/ctrl-s-hang-terminal-emulator
  match "*path", to: "application#routing_error", via: :all
end

app/views/layouts/admin.haml
!!!
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type'}/
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0'}/
    %title Miteinander: das Phrasenbuch
    = favicon_link_tag
    = stylesheet_link_tag    'admin', media: 'all'
    = javascript_include_tag 'admin'
    = csrf_meta_tags
    = google_webfonts_init font_list # Liste ist im Helper!
  %body
    %header
      = image_tag 'schriftzug.png', alt: 'Miteinander – Das Phrasenbuch'
    %section
      %aside
        = render 'admin/shared/phraselist'
      %article
        = yield
    %footer

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type'}/
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0'}/
    %title= t(:appname, default: 'The Miteinander Phrasebook')
    = render 'favicon'
    = stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': true
    = javascript_include_tag 'vendor/modernizr'
    = javascript_include_tag 'admin', 'data-turbolinks-track': true
    = csrf_meta_tags
    = google_webfonts_init font_list # Liste ist im Helper!
  %body{id: controller_as_id}
    %header#header
      = render 'logo'
      - flash.each do |t,msg|
        %div{class: "flash flash-#{t}"}= msg
      %nav
        = link_to_menu_item t('.phrases', default: 'Phrases'), admin_phrases_path
        = link_to_menu_item t('.tags', default: 'Tags'), admin_tags_path
        = link_to_menu_item t('.searches', default: 'Search Requests'), admin_searches_path
        = link_to_menu_item t('.users', default: 'Users'), admin_users_path
        = link_to_sign_in_or_out
    %main
      - if content_for? :aside
        %aside{id: "#{model_as_id}_list",}
          = yield :aside
      %article{id: model_as_id}
        = yield :article

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type'}/
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0'}/
    %title= t(:appname, default: 'The Miteinander Phrasebook')
    = render 'favicon'
    = google_webfonts_init(font_list) # Liste ist im Helper!
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': true
    = javascript_include_tag 'vendor/modernizr', 'data-turbolinks-track': true
    = javascript_include_tag 'application', 'data-turbolinks-track': true
    = csrf_meta_tags
  %body
    %header
      = render 'logo'
      %nav
        %ul
          %li= link_to_menu_item fa_icon('list'), phrases_path, title: t('.phrases', default: 'Phrase list')
          %li= link_to_menu_item fa_icon('map-signs'), page_path(:tag_directory), title: t('.tag_directory', default: 'Tag directory')
          %li= link_to_menu_item fa_icon('info-circle'), page_path(:imprint), title: t('.imprint', default: 'Imprint')
          %li= link_to_sign_in_or_out
      = show_flashes
    %main
      %article{id: controller_and_action, class: "#{controller_as_id}_#{params[:id]}"}
        = yield
      %footer
        = image_tag("beta_banner.#{I18n.locale}.png", id: 'beta_banner')